version: "2"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: db
  app:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      POSTGRES_HOST: db
